# Project information
site_name: AI Research
site_author: Erik Novak
site_description: >-
  The documentation to help start students and researchers on their
  journey to doing research and publish papers.

# Repository
repo_name: eriknovak/docs-research
repo_url: https://github.com/eriknovak/docs-research

# Copyright
copyright: ""

# Configuration
theme:
  name: material
  features:
    - content.code.copy
    - content.code.annotate
    - content.tooltips
    - navigation.indexes
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    # Palette toggle for light
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # Palette toggle for dark
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: white
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  logo: assets/imgs/logo.png

edit_uri: ""

# Plugins
plugins:
  - search

# Markdown Extensions
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/E3-JSI
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/AiLab_JSI
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/ailab-at-jsi-3ab15937/

# Page tree
nav:
  - Home: index.md

  - Run an Experiment:
      - How to Start: experiments/how-to-start.md
      - Technology Stack: experiments/technology-stack.md
      - 🚧 Machines for Development: experiments/machines-for-development.md
      - 🚧 Experiment Examples: experiments/experiment-examples.md

  - Write a Paper:
      - How to Start: papers/how-to-start.md
      - Paper Structure: papers/paper-structure.md
      - Journals: papers/journals.md
      - 🚧 Conferences: papers/conferences.md
