# Project information
site_name: E3 JSI Research
site_author: Erik Novak
site_description: >-
  The documentation to help start students and researchers on their
  journey to doing research and publish papers.

# Repository
repo_name: eriknovak/docs-research
repo_url: https://github.com/eriknovak/docs-research

# Copyright
copyright: Copyright &copy; 2022 - 2023 E3 JSI Research

# Configuration
theme:
  name: material
  features:
    - content.code.annotate
    - content.tooltips
    - navigation.indexes
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  logo: assets/imgs/logo.png

edit_uri: ""

# Plugins
plugins:
  - search

# Markdown Extensions
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/E3-JSI
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/AiLab_JSI
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/ailab-at-jsi-3ab15937/

# Page tree
nav:
  - Home: index.md
  
  - Run Experiments:
      - How to Start: experiments/how-to-start.md
      - Tech Stack: experiments/tech-stack.md

  - Write a Paper:
      - How to Start: papers/how-to-start.md
      - Paper Structure: papers/paper-structure.md
      - Journals: papers/journals.md

